[envs.default]
installer = "uv"

[envs.types]
extra-dependencies = [
  "mypy",
  "pytest",
]
[envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/dep_sync tests}"

[envs.hatch-static-analysis]
config-path = "ruff_defaults.toml"

[envs.hatch-test]
extra-dependencies = [
  "uv",
]

[envs.docs]
dependencies = [
  "mkdocs~=1.6.1",
  "mkdocs-material~=9.5.34",
  # Plugins
  "mkdocs-minify-plugin~=0.8.0",
  "mkdocs-git-revision-date-localized-plugin~=1.2.9",
  "mkdocstrings-python~=1.11.1",
  # Extensions
  "pymdown-extensions~=10.8.0",
  # Necessary for syntax highlighting in code blocks
  "pygments~=2.18.0",
  # Validation
  # https://github.com/linkchecker/linkchecker/pull/669#issuecomment-1267236287
  "linkchecker @ git+https://github.com/linkchecker/linkchecker.git@d9265bb71c2054bf57b8c5734a4825d62505c779",
]
[envs.docs.env-vars]
SOURCE_DATE_EPOCH = "1580601600"
[envs.docs.scripts]
build = "mkdocs build --clean --strict {args}"
serve = "mkdocs serve --dev-addr localhost:8000 {args}"
validate = "linkchecker --config .linkcheckerrc site"
# https://github.com/linkchecker/linkchecker/issues/678
build-check = [
  "build --no-directory-urls",
  "validate",
]
